### ISSUE TITLE
Issue while Beta-testing.

### ISSUE THREAD

**Issue by Lucario14** [TheCrafters001/TF2-Mod-Installer#2]
![image](https://user-images.githubusercontent.com/81989287/113613633-df596200-9627-11eb-8931-c24ade92a9e6.png)
Had this issue while beta-testing this.

It seems to happen in every HUD mod.

It seems promising, i hope there is a solution to this.

**Comment by TheCrafters001** [comment]
Patched with commit 4034534622a0cb3f54f9d39ca12d39dc97475d3f
